jobs:
  browser-tests-macos:
    name: Browser Tests
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos
    uses: ./.github/workflows/bazel.yml
    with:
      browser: chrome
      cache-key: java-${{ matrix.os }}-tests
      java-version: 17
      name: Browser Tests (chrome, ${{ matrix.os }})
      os: ${{ matrix.os }}
      run: "bazel test --flaky_test_attempts 3 //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest-remote\
        \ \\\n    //java/test/org/openqa/selenium/federatedcredentialmanagement:FederatedCredentialManagementTest\
        \ \\\n  //java/test/org/openqa/selenium/firefox:FirefoxDriverBuilderTest \\\
        \n    //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest\
        \ \\\n    //java/test/org/openqa/selenium/remote:RemoteWebDriverBuilderTest\
        \ \\\n    //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest\n"
  browser-tests-windows:
    name: Browser Tests
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows
    uses: ./.github/workflows/bazel.yml
    with:
      browser: chrome
      cache-key: java-${{ matrix.os }}-tests
      java-version: 17
      name: Browser Tests (chrome, ${{ matrix.os }})
      os: ${{ matrix.os }}
      run: "bazel test --flaky_test_attempts 3 //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest\
        \ `\n    //java/test/org/openqa/selenium/federatedcredentialmanagement:FederatedCredentialManagementTest\
        \ `\n    //java/test/org/openqa/selenium/firefox:FirefoxDriverBuilderTest\
        \ `\n    //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest\
        \ `\n    //java/test/org/openqa/selenium/remote:RemoteWebDriverBuilderTest\
        \ `\n    //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest\n"
  remote-tests:
    name: Remote Tests
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos
    uses: ./.github/workflows/bazel.yml
    with:
      browser: chrome
      cache-key: java-${{ matrix.os }}-remote-tests
      java-version: 17
      name: Remote Tests (chrome, ${{ matrix.os }})
      os: ${{ matrix.os }}
      run: 'bazel test --flaky_test_attempts 3 //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest-remote

        '
name: CI - Java
on:
  repository_dispatch:
    types: trigger-ga___ci-java.yml
