jobs:
  browser-tests:
    name: Browser Tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        browser:
        - chrome
        - firefox
    uses: ./.github/workflows/bazel.yml
    with:
      browser: ${{ matrix.browser }}
      cache-key: javascript-${{matrix.browser}}-browser-tests
      name: Browser Tests  (${{ matrix.browser }})
      run: 'bazel test --flaky_test_attempts 3 --test_tag_filters ${{ matrix.browser
        }} //javascript/node/...

        '
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: javascript-build
      name: Build
      run: bazel build //javascript/node/selenium-webdriver:selenium-webdriver
name: CI - JavaScript
on:
  repository_dispatch:
    types: trigger-ga___ci-javascript.yml
