jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: py-build
      name: Build
      run: bazel build //py:selenium-wheel //py:selenium-sdist
  docs:
    name: Documentation
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source tree
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install tox==4.6.4

        '
    - continue-on-error: true
      env:
        TOXENV: docs
      name: Test with tox
      run: tox -c py/tox.ini
  lint:
    name: Lint
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source tree
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install tox==4.6.4

        '
    - continue-on-error: true
      env:
        TOXENV: linting-ci
      name: Test with tox
      run: tox -c py/tox.ini
  mypy:
    name: Mypy
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source tree
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - continue-on-error: true
      name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install tox==4.6.4

        '
    - continue-on-error: true
      env:
        TOXENV: mypy
      name: Test with tox
      run: 'tox -c py/tox.ini -- --cobertura-xml-report ci || true

        bash <(curl -s https://codecov.io/bash) -f py/ci/cobertura.xml

        '
  remote-tests:
    name: Remote Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      browser: firefox
      cache-key: py-remote
      name: Integration Tests (remote)
      run: bazel test --local_test_jobs 1 --flaky_test_attempts 3 //py:test-remote
name: CI - Python
on:
  repository_dispatch:
    types: trigger-ga___ci-python.yml
