jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: rb-build
      name: Build
      run: bazel build //rb:selenium-devtools //rb:selenium-webdriver
  docs:
    name: Documentation
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: rb-docs
      name: Documentation
      run: bazel run //rb:docs
  integration-tests-local:
    name: Local Tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        browser:
        - chrome
        - edge
        - firefox
        exclude:
        - browser: edge
          os: ubuntu
        - browser: edge
          os: macos
        os:
        - ubuntu
        - windows
        - macos
    uses: ./.github/workflows/bazel.yml
    with:
      browser: ${{ matrix.browser }}
      cache-key: rb-${{ matrix.browser }}-test
      name: Local Tests (${{ matrix.browser }}, ${{ matrix.os }})
      os: ${{ matrix.os }}
      run: 'bazel test --build_tests_only --flaky_test_attempts 3 --local_test_jobs
        1 --test_size_filters large --test_tag_filters ${{ matrix.browser }} //rb/spec/...

        '
  integration-tests-remote:
    name: Remote Tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - browser: edge
          os: windows
        - browser: chrome
          os: ubuntu
        - browser: firefox
          os: ubuntu
    uses: ./.github/workflows/bazel.yml
    with:
      browser: ${{ matrix.browser }}
      cache-key: rb-remote-${{ matrix.browser }}-test
      java-version: 11
      name: Remote Tests (${{ matrix.browser }}, ${{ matrix.os }})
      os: ${{ matrix.os }}
      run: 'bazel test --build_tests_only --flaky_test_attempts 3 --local_test_jobs
        1 --test_size_filters large --test_tag_filters ${{ matrix.browser }}-remote
        //rb/spec/...

        '
  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: rb-lint
      name: Lint
      run: bazel test //rb:lint
  unit-tests:
    name: Unit Tests
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu
          ruby-version: 3.0.6
        - os: windows
          ruby-version: 3.0.6
        - os: macos
          ruby-version: 3.0.6
        - os: ubuntu
          ruby-version: 3.3.0
        - os: ubuntu
          ruby-version: jruby-9.4.5.0
        - os: ubuntu
          ruby-version: truffleruby-23.1.1
    uses: ./.github/workflows/bazel.yml
    with:
      cache-key: rb-unit-test-${{ matrix.ruby-version }}
      name: Unit Tests (${{ matrix.ruby-version }}, ${{ matrix.os }})
      os: ${{ matrix.os }}
      ruby-version: ${{ matrix.ruby-version }}
      run: 'bazel test --build_tests_only --test_size_filters small //rb/spec/...

        '
name: CI - Ruby
on:
  repository_dispatch:
    types: trigger-ga___ci-ruby.yml
