jobs:
  check:
    name: Check
    outputs:
      targets: ${{ steps.check-targets.outputs.bazel-targets }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source tree
      uses: actions/checkout@v4
      with:
        fetch-depth: 50
    - continue-on-error: true
      name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.8.5
      with:
        bazelisk-cache: true
        cache-version: 2
        external-cache: "name: ci-check\nmanifest:\n  crates: rust/Cargo.Bazel.lock\n\
          \  rules_ruby~~ruby~ruby: rb/.ruby-version\n"
        repository-cache: true
    - continue-on-error: true
      env:
        COMMIT_RANGE: ${{ github.event.pull_request.base.sha || github.event.before
          }}...${{ github.event.pull_request.head.sha || github.sha }}
      id: check-targets
      name: Check Bazel targets
      run: ./scripts/github-actions/check-bazel-targets.sh
  dotnet:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//dotnet'') || contains(join(github.event.commits.*.message),
      ''[dotnet]'') || contains(github.event.pull_request.title, ''[dotnet]'')

      '
    name: .NET
    needs: check
    uses: ./.github/workflows/ci-dotnet.yml
  java:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//java'') || contains(join(github.event.commits.*.message),
      ''[java]'') || contains(github.event.pull_request.title, ''[java]'')

      '
    name: Java
    needs: check
    uses: ./.github/workflows/ci-java.yml
  javascript:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//javascript'') || contains(join(github.event.commits.*.message),
      ''[js]'') || contains(github.event.pull_request.title, ''[js]'')

      '
    name: JavaScript
    needs: check
    uses: ./.github/workflows/ci-javascript.yml
  python:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//py'') || contains(join(github.event.commits.*.message),
      ''[py]'') || contains(github.event.pull_request.title, ''[py]'')

      '
    name: Python
    needs: check
    uses: ./.github/workflows/ci-python.yml
  ruby:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//rb'') || contains(join(github.event.commits.*.message),
      ''[rb]'') || contains(github.event.pull_request.title, ''[rb]'')

      '
    name: Ruby
    needs: check
    uses: ./.github/workflows/ci-ruby.yml
  rust:
    if: 'github.event_name == ''schedule'' || github.event_name == ''workflow_dispatch''
      || contains(needs.check.outputs.targets, ''//rust'') || contains(join(github.event.commits.*.message),
      ''[rust]'') || contains(github.event.pull_request.title, ''[rust]'')

      '
    name: Rust
    needs: check
    secrets:
      SELENIUM_CI_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
    uses: ./.github/workflows/ci-rust.yml
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
