jobs:
  pull-request:
    if: github.repository_owner == 'seleniumhq'
    needs: update
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Download patch
      uses: actions/download-artifact@v4
      with:
        name: pinned-browsers
    - continue-on-error: true
      name: Apply Patch
      run: 'git apply changes.patch

        rm changes.patch

        '
    - continue-on-error: true
      name: Check Changes
      run: 'if [[ -n $(git status --porcelain common/repositories.bzl) ]]; then

        echo "CHANGES_FOUND=true" >> $GITHUB_ENV

        fi

        '
    - continue-on-error: true
      if: env.CHANGES_FOUND == 'true'
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        add-paths: common/repositories.bzl
        author: Selenium CI Bot <selenium-ci@users.noreply.github.com>
        body: 'This is an automated pull request to update pinned browsers and drivers


          Merge after verify the new browser versions properly passing the tests and
          no bugs need to be filed

          '
        branch: pinned-browser-updates
        commit-message: Update pinned browser versions
        committer: Selenium CI Bot <selenium-ci@users.noreply.github.com>
        title: '[dotnet][rb][java][js][py] Automated Browser Version Update'
        token: ${{ secrets.SELENIUM_CI_TOKEN }}
  update:
    name: Update Pinned Browsers
    uses: ./.github/workflows/bazel.yml
    with:
      artifact-name: pinned-browsers
      cache-key: pin-browsers
      name: Pin Browsers
      run: bazel run //scripts:pinned_browsers
name: Pin Browsers
on:
  repository_dispatch:
    types: trigger-ga___pin-browsers.yml
