jobs:
  selenium-manager:
    name: Release Selenium Manager
    needs: update-rust
    secrets:
      SELENIUM_CI_TOKEN: ${{ secrets.SELENIUM_CI_TOKEN }}
    uses: ./.github/workflows/ci-rust.yml
    with:
      branch: release-${{ github.event.inputs.version }}
      release: true
  update-files:
    name: Update Files
    needs: selenium-manager
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false
        ref: release-${{ github.event.inputs.version }}
    - continue-on-error: true
      name: Install Ruby
      uses: ruby/setup-ruby@d5fb7a202fc07872cb44f00ba8e6197b70cb0c55
      with:
        ruby-version: '3.1'
        working-directory: rb
    - continue-on-error: true
      name: Prep git
      run: 'git config --local user.email "selenium-ci@users.noreply.github.com"

        git config --local user.name "Selenium CI Bot"

        '
    - continue-on-error: true
      name: Undo rust changelog commit
      run: git reset HEAD~1
    - continue-on-error: true
      if: ${{ github.event.inputs.chrome_channel == 'early-stable' }}
      name: Update everything including early release CDP
      run: ./go all:prepare['Beta']
    - continue-on-error: true
      if: ${{ github.event.inputs.chrome_channel == 'stable' }}
      name: Update everything including released CDP
      run: ./go "all:prepare[Stable]"
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        author: Selenium CI Bot <selenium-ci@users.noreply.github.com>
        base: trunk
        body: "**Warning: Manually update the changelogs before merging**\n\nThis\
          \ PR:\n  * Updates Rust version for Selenium Manager release\n  * Updates\
          \ Pinned browser version to coincide with new CDP release\n  * Adds support\
          \ for new CDP version and removes old CDP version\n  * Selenium Manager\
          \ references the new Selenium Manager release\n  * Updates Maven Dependencies\n\
          \  * Adds new authors to authors file\n  * Updates all versions for all\
          \ bindings\n  * Generates *rough* change logs for each bindings (please\
          \ tidy them up before merging this)\n\n- Auto-generated by [create-pull-request][1]\n\
          \n[1]: https://github.com/peter-evans/create-pull-request\n"
        branch: release-preparation-${{ github.event.inputs.version }}
        delete-branch: true
        draft: true
        labels: C-build
        title: '[build] Prepare for release of Selenium ${{ github.event.inputs.version
          }}'
        token: ${{ secrets.SELENIUM_CI_TOKEN }}
  update-rust:
    name: Update Rust Version
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        persist-credentials: false
    - continue-on-error: true
      name: Prep git
      run: 'git config --local user.email "selenium-ci@users.noreply.github.com"

        git config --local user.name "Selenium CI Bot"

        if git rev-parse --verify release-${{ github.event.inputs.version }} >/dev/null
        2>&1; then

        git branch -D release-${{ github.event.inputs.version }}

        fi

        git checkout -b release-${{ github.event.inputs.version }}

        '
    - continue-on-error: true
      name: Update Rust Version
      run: './go rust:version

        ./go rust:version:commit

        '
    - continue-on-error: true
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: release-${{ github.event.inputs.version }}
        force: true
        github_token: ${{ secrets.SELENIUM_CI_TOKEN }}
name: Release Preparation
on:
  repository_dispatch:
    types: trigger-ga___pre-release.yml
