jobs:
  stale:
    if: github.repository_owner == 'seleniumhq'
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: This issue was closed because it has been stalled for
          14 days with no activity.
        days-before-close: 14
        days-before-stale: 280
        stale-issue-label: I-stale
        stale-issue-message: This issue is stale because it has been open 280 days
          with no activity. Remove stale label or comment or this will be closed in
          14 days.
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        close-issue-message: This issue was closed because we did not receive any
          additional information after 14 days.
        days-before-close: 14
        days-before-stale: -1
        labels-to-add-when-unstale: needs-triaging
        stale-issue-label: R-awaiting answer
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
